// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using YaVDele.Domain.DbContexts;

namespace YaVDele.Domain.Migrations
{
    [DbContext(typeof(YaVDeleDbContext))]
    [Migration("20200620141837_VkUserAvatarUrl")]
    partial class VkUserAvatarUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("YaVDele.Domain.Entities.YaVDeleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnName("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("character varying(1023)")
                        .HasMaxLength(1023);

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnName("location")
                        .HasColumnType("geography (point)");

                    b.Property<int>("MaxQuantiyty")
                        .HasColumnName("max_quantiyty")
                        .HasColumnType("integer");

                    b.Property<bool>("Revoked")
                        .HasColumnName("revoked")
                        .HasColumnType("boolean");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("YaVDeleUserOwnerId")
                        .HasColumnName("ya_v_dele_user_owner_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector")
                        .HasAnnotation("Npgsql:IndexMethod", "GIN");

                    b.HasIndex("YaVDeleUserOwnerId");

                    b.ToTable("ya_v_dele_events");
                });

            modelBuilder.Entity("YaVDele.Domain.Entities.YaVDeleUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<bool>("GuideCompleted")
                        .HasColumnName("guide_completed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.Property<long>("VkId")
                        .HasColumnName("vk_id")
                        .HasColumnType("bigint");

                    b.Property<string>("VkUserAvatarUrl")
                        .HasColumnName("vk_user_avatar_url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VkId")
                        .IsUnique();

                    b.ToTable("ya_v_dele_users");
                });

            modelBuilder.Entity("YaVDele.Domain.Entities.YaVDeleEvent", b =>
                {
                    b.HasOne("YaVDele.Domain.Entities.YaVDeleUser", "YaVDeleUserOwner")
                        .WithMany("OwnYaVDeleEvents")
                        .HasForeignKey("YaVDeleUserOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
