export const PANELS = {
    FIND_NEAR_ME_PANEL: 'Find like-minded person near myself',
    MY_PROFILE_PANEL: 'Panel for my profile',
    CREATE_EVENT_PANEL: 'Create event panel',
    MENU_PANEL: 'Menu panel',
    EVENTS_NEAR_ME_MAP_PANEL: 'EVENTS_NEAR_ME_PANEL_MAP',
    EVENTS_NEAR_ME_LIST_PANEL: 'EVENTS_NEAR_ME_PANEL_CATALOG',
    HELLO_INTRO_PANEL: 'HELLO_INTRO_PANEL',
    PROFILE_INTRO_PANEL: 'PROFILE_INTRO_PANEL',
};
