export const TABS = {
    APPLICATIONS_I_WILL_GO: 'APPLICATIONS_I_WILL_GO',
    APPLICATIONS_REJECTED: 'APPLICATIONS_REJECTED',
    SENT_APPLICATIONS: 'SENT_APPLICATIONS',
    VISITED_APPLICATIONS: 'VISITED_APPLICATIONS',
    EVENTS_MAP: 'EVENTS_MAP',
    EVENTS_LIST: 'EVENTS_LIST'
};
